language: c
compiler:
  - gcc
before_install:
  - sudo apt-get install freeglut3-dev libsdl1.2-dev libsdl-mixer1.2-dev
  - sudo pip install cpp-coveralls
script:
  - ./configure --enable-gcov && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'